/**
 * @file syscall_defs.h
 * @brief Syscall definitions and types.
 */

#ifndef  SYSCALL_DEFS_H
# define SYSCALL_DEFS_H

// ---
// Includes
// ---

# include "utils.h"

// ---
// Defines
// ---

/**
 * @brief Maximum number of syscall arguments.
 */
# define MAX_SYSCALL_ARG_COUNT (6)

/**
 * @brief Decode sys_type.
 */
# define GET_SYS_TYPE(sys_type) (ABS(sys_type) & 0xff)

/**
 * @brief Decode SYS_TYPE arg (like MEMSEG)
 */
# define GET_SYS_TYPE_ARG(sys_type) (ABS(sys_type) >> 8)

/**
 * @brief Encode SYS_TYPE with arg (like MEMSEG)
 */
# define SYS_TYPE_ARG(sys_type, sys_arg) ((sys_type) | (sys_arg << 8))

# define SYS_TYPE_DEFAULT (SYS_TYPE_INT) /**< Alias for SYS_TYPE_INT. */

// ---
// Typedefs
// ---

/**
 * @typedef syscall_type_t
 * @brief Syscall argument types for logging.
 */
typedef enum syscall_type_e {
	SYS_TYPE_NONE = 0,   /**< No type / unused argument. */
	SYS_TYPE_INT,        /**< Unsigned integer. */
	SYS_TYPE_SIGNED_INT, /**< Signed integer. */
	SYS_TYPE_HEX,        /**< Hexadecimal value. */
	SYS_TYPE_PTR,        /**< Pointer. */
	SYS_TYPE_STRING,     /**< String pointer. */
	SYS_TYPE_MEMSEG,     /**< Memory segment. */
	SYS_TYPE_OPEN_FLAGS, /**< open() flags. */
	SYS_TYPE_OPEN_MODE,  /**< open() mode. */
	SYS_TYPE__COUNT      /**< Number of types. */
}	syscall_type_t;

/**
 * @typedef syscall_def_t
 * @brief Syscall definition.
 */
typedef struct syscall_def_s {
	/**
	 * @brief Syscall name.
	 */
	const char			*name;

	/**
	 * @brief Return type.
	 */
	syscall_type_t		ret_type;

	/**
	 * @brief Argument types.
	 */
	syscall_type_t		arg_types[MAX_SYSCALL_ARG_COUNT];
}	syscall_def_t;

/**
 * @brief Syscall reference indices.
 */
enum {
SR_SYS_accept,
SR_SYS_accept4,
SR_SYS_access,
SR_SYS_acct,
SR_SYS_add_key,
SR_SYS_adjtimex,
SR_SYS_afs_syscall,
SR_SYS_alarm,
SR_SYS_arch_prctl,
SR_SYS_bdflush,
SR_SYS_bind,
SR_SYS_bpf,
SR_SYS_break,
SR_SYS_brk,
SR_SYS_capget,
SR_SYS_capset,
SR_SYS_chdir,
SR_SYS_chmod,
SR_SYS_chown,
SR_SYS_chown32,
SR_SYS_chroot,
SR_SYS_clock_adjtime,
SR_SYS_clock_adjtime64,
SR_SYS_clock_getres,
SR_SYS_clock_getres_time64,
SR_SYS_clock_gettime,
SR_SYS_clock_gettime64,
SR_SYS_clock_nanosleep,
SR_SYS_clock_nanosleep_time64,
SR_SYS_clock_settime,
SR_SYS_clock_settime64,
SR_SYS_clone,
SR_SYS_clone3,
SR_SYS_close,
SR_SYS_close_range,
SR_SYS_connect,
SR_SYS_copy_file_range,
SR_SYS_creat,
SR_SYS_create_module,
SR_SYS_delete_module,
SR_SYS_dup,
SR_SYS_dup2,
SR_SYS_dup3,
SR_SYS_epoll_create,
SR_SYS_epoll_create1,
SR_SYS_epoll_ctl,
SR_SYS_epoll_ctl_old,
SR_SYS_epoll_pwait,
SR_SYS_epoll_pwait2,
SR_SYS_epoll_wait,
SR_SYS_epoll_wait_old,
SR_SYS_eventfd,
SR_SYS_eventfd2,
SR_SYS_execve,
SR_SYS_execveat,
SR_SYS_exit,
SR_SYS_exit_group,
SR_SYS_faccessat,
SR_SYS_faccessat2,
SR_SYS_fadvise64,
SR_SYS_fadvise64_64,
SR_SYS_fallocate,
SR_SYS_fanotify_init,
SR_SYS_fanotify_mark,
SR_SYS_fchdir,
SR_SYS_fchmod,
SR_SYS_fchmodat,
SR_SYS_fchown,
SR_SYS_fchown32,
SR_SYS_fchownat,
SR_SYS_fcntl,
SR_SYS_fcntl64,
SR_SYS_fdatasync,
SR_SYS_fgetxattr,
SR_SYS_finit_module,
SR_SYS_flistxattr,
SR_SYS_flock,
SR_SYS_fork,
SR_SYS_fremovexattr,
SR_SYS_fsconfig,
SR_SYS_fsetxattr,
SR_SYS_fsmount,
SR_SYS_fsopen,
SR_SYS_fspick,
SR_SYS_fstat,
SR_SYS_fstat64,
SR_SYS_fstatat64,
SR_SYS_fstatfs,
SR_SYS_fstatfs64,
SR_SYS_fsync,
SR_SYS_ftime,
SR_SYS_ftruncate,
SR_SYS_ftruncate64,
SR_SYS_futex,
SR_SYS_futex_time64,
SR_SYS_futimesat,
SR_SYS_getcpu,
SR_SYS_getcwd,
SR_SYS_getdents,
SR_SYS_getdents64,
SR_SYS_getegid,
SR_SYS_getegid32,
SR_SYS_geteuid,
SR_SYS_geteuid32,
SR_SYS_getgid,
SR_SYS_getgid32,
SR_SYS_getgroups,
SR_SYS_getgroups32,
SR_SYS_getitimer,
SR_SYS_get_kernel_syms,
SR_SYS_get_mempolicy,
SR_SYS_getpeername,
SR_SYS_getpgid,
SR_SYS_getpgrp,
SR_SYS_getpid,
SR_SYS_getpmsg,
SR_SYS_getppid,
SR_SYS_getpriority,
SR_SYS_getrandom,
SR_SYS_getresgid,
SR_SYS_getresgid32,
SR_SYS_getresuid,
SR_SYS_getresuid32,
SR_SYS_getrlimit,
SR_SYS_get_robust_list,
SR_SYS_getrusage,
SR_SYS_getsid,
SR_SYS_getsockname,
SR_SYS_getsockopt,
SR_SYS_get_thread_area,
SR_SYS_gettid,
SR_SYS_gettimeofday,
SR_SYS_getuid,
SR_SYS_getuid32,
SR_SYS_getxattr,
SR_SYS_gtty,
SR_SYS_idle,
SR_SYS_init_module,
SR_SYS_inotify_add_watch,
SR_SYS_inotify_init,
SR_SYS_inotify_init1,
SR_SYS_inotify_rm_watch,
SR_SYS_io_cancel,
SR_SYS_ioctl,
SR_SYS_io_destroy,
SR_SYS_io_getevents,
SR_SYS_ioperm,
SR_SYS_io_pgetevents,
SR_SYS_io_pgetevents_time64,
SR_SYS_iopl,
SR_SYS_ioprio_get,
SR_SYS_ioprio_set,
SR_SYS_io_setup,
SR_SYS_io_submit,
SR_SYS_io_uring_enter,
SR_SYS_io_uring_register,
SR_SYS_io_uring_setup,
SR_SYS_ipc,
SR_SYS_kcmp,
SR_SYS_kexec_file_load,
SR_SYS_kexec_load,
SR_SYS_keyctl,
SR_SYS_kill,
SR_SYS_landlock_add_rule,
SR_SYS_landlock_create_ruleset,
SR_SYS_landlock_restrict_self,
SR_SYS_lchown,
SR_SYS_lchown32,
SR_SYS_lgetxattr,
SR_SYS_link,
SR_SYS_linkat,
SR_SYS_listen,
SR_SYS_listxattr,
SR_SYS_llistxattr,
SR_SYS__llseek,
SR_SYS_lock,
SR_SYS_lookup_dcookie,
SR_SYS_lremovexattr,
SR_SYS_lseek,
SR_SYS_lsetxattr,
SR_SYS_lstat,
SR_SYS_lstat64,
SR_SYS_madvise,
SR_SYS_mbind,
SR_SYS_membarrier,
SR_SYS_memfd_create,
SR_SYS_memfd_secret,
SR_SYS_migrate_pages,
SR_SYS_mincore,
SR_SYS_mkdir,
SR_SYS_mkdirat,
SR_SYS_mknod,
SR_SYS_mknodat,
SR_SYS_mlock,
SR_SYS_mlock2,
SR_SYS_mlockall,
SR_SYS_mmap,
SR_SYS_mmap2,
SR_SYS_modify_ldt,
SR_SYS_mount,
SR_SYS_mount_setattr,
SR_SYS_move_mount,
SR_SYS_move_pages,
SR_SYS_mprotect,
SR_SYS_mpx,
SR_SYS_mq_getsetattr,
SR_SYS_mq_notify,
SR_SYS_mq_open,
SR_SYS_mq_timedreceive,
SR_SYS_mq_timedreceive_time64,
SR_SYS_mq_timedsend,
SR_SYS_mq_timedsend_time64,
SR_SYS_mq_unlink,
SR_SYS_mremap,
SR_SYS_msgctl,
SR_SYS_msgget,
SR_SYS_msgrcv,
SR_SYS_msgsnd,
SR_SYS_msync,
SR_SYS_munlock,
SR_SYS_munlockall,
SR_SYS_munmap,
SR_SYS_name_to_handle_at,
SR_SYS_nanosleep,
SR_SYS_newfstatat,
SR_SYS__newselect,
SR_SYS_nfsservctl,
SR_SYS_nice,
SR_SYS_oldfstat,
SR_SYS_oldlstat,
SR_SYS_oldolduname,
SR_SYS_oldstat,
SR_SYS_olduname,
SR_SYS_open,
SR_SYS_openat,
SR_SYS_openat2,
SR_SYS_open_by_handle_at,
SR_SYS_open_tree,
SR_SYS_pause,
SR_SYS_perf_event_open,
SR_SYS_personality,
SR_SYS_pidfd_getfd,
SR_SYS_pidfd_open,
SR_SYS_pidfd_send_signal,
SR_SYS_pipe,
SR_SYS_pipe2,
SR_SYS_pivot_root,
SR_SYS_pkey_alloc,
SR_SYS_pkey_free,
SR_SYS_pkey_mprotect,
SR_SYS_poll,
SR_SYS_ppoll,
SR_SYS_ppoll_time64,
SR_SYS_prctl,
SR_SYS_pread64,
SR_SYS_preadv,
SR_SYS_preadv2,
SR_SYS_prlimit64,
SR_SYS_process_madvise,
SR_SYS_process_mrelease,
SR_SYS_process_vm_readv,
SR_SYS_process_vm_writev,
SR_SYS_prof,
SR_SYS_profil,
SR_SYS_pselect6,
SR_SYS_pselect6_time64,
SR_SYS_ptrace,
SR_SYS_putpmsg,
SR_SYS_pwrite64,
SR_SYS_pwritev,
SR_SYS_pwritev2,
SR_SYS_query_module,
SR_SYS_quotactl,
SR_SYS_quotactl_fd,
SR_SYS_read,
SR_SYS_readahead,
SR_SYS_readdir,
SR_SYS_readlink,
SR_SYS_readlinkat,
SR_SYS_readv,
SR_SYS_reboot,
SR_SYS_recvfrom,
SR_SYS_recvmmsg,
SR_SYS_recvmmsg_time64,
SR_SYS_recvmsg,
SR_SYS_remap_file_pages,
SR_SYS_removexattr,
SR_SYS_rename,
SR_SYS_renameat,
SR_SYS_renameat2,
SR_SYS_request_key,
SR_SYS_restart_syscall,
SR_SYS_rmdir,
SR_SYS_rseq,
SR_SYS_rt_sigaction,
SR_SYS_rt_sigpending,
SR_SYS_rt_sigprocmask,
SR_SYS_rt_sigqueueinfo,
SR_SYS_rt_sigreturn,
SR_SYS_rt_sigsuspend,
SR_SYS_rt_sigtimedwait,
SR_SYS_rt_sigtimedwait_time64,
SR_SYS_rt_tgsigqueueinfo,
SR_SYS_sched_getaffinity,
SR_SYS_sched_getattr,
SR_SYS_sched_getparam,
SR_SYS_sched_get_priority_max,
SR_SYS_sched_get_priority_min,
SR_SYS_sched_getscheduler,
SR_SYS_sched_rr_get_interval,
SR_SYS_sched_rr_get_interval_time64,
SR_SYS_sched_setaffinity,
SR_SYS_sched_setattr,
SR_SYS_sched_setparam,
SR_SYS_sched_setscheduler,
SR_SYS_sched_yield,
SR_SYS_seccomp,
SR_SYS_security,
SR_SYS_select,
SR_SYS_semctl,
SR_SYS_semget,
SR_SYS_semop,
SR_SYS_semtimedop,
SR_SYS_semtimedop_time64,
SR_SYS_sendfile,
SR_SYS_sendfile64,
SR_SYS_sendmmsg,
SR_SYS_sendmsg,
SR_SYS_sendto,
SR_SYS_setdomainname,
SR_SYS_setfsgid,
SR_SYS_setfsgid32,
SR_SYS_setfsuid,
SR_SYS_setfsuid32,
SR_SYS_setgid,
SR_SYS_setgid32,
SR_SYS_setgroups,
SR_SYS_setgroups32,
SR_SYS_sethostname,
SR_SYS_setitimer,
SR_SYS_set_mempolicy,
SR_SYS_setns,
SR_SYS_setpgid,
SR_SYS_setpriority,
SR_SYS_setregid,
SR_SYS_setregid32,
SR_SYS_setresgid,
SR_SYS_setresgid32,
SR_SYS_setresuid,
SR_SYS_setresuid32,
SR_SYS_setreuid,
SR_SYS_setreuid32,
SR_SYS_setrlimit,
SR_SYS_set_robust_list,
SR_SYS_setsid,
SR_SYS_setsockopt,
SR_SYS_set_thread_area,
SR_SYS_set_tid_address,
SR_SYS_settimeofday,
SR_SYS_setuid,
SR_SYS_setuid32,
SR_SYS_setxattr,
SR_SYS_sgetmask,
SR_SYS_shmat,
SR_SYS_shmctl,
SR_SYS_shmdt,
SR_SYS_shmget,
SR_SYS_shutdown,
SR_SYS_sigaction,
SR_SYS_sigaltstack,
SR_SYS_signal,
SR_SYS_signalfd,
SR_SYS_signalfd4,
SR_SYS_sigpending,
SR_SYS_sigprocmask,
SR_SYS_sigreturn,
SR_SYS_sigsuspend,
SR_SYS_socket,
SR_SYS_socketcall,
SR_SYS_socketpair,
SR_SYS_splice,
SR_SYS_ssetmask,
SR_SYS_stat,
SR_SYS_stat64,
SR_SYS_statfs,
SR_SYS_statfs64,
SR_SYS_statx,
SR_SYS_stime,
SR_SYS_stty,
SR_SYS_swapoff,
SR_SYS_swapon,
SR_SYS_symlink,
SR_SYS_symlinkat,
SR_SYS_sync,
SR_SYS_sync_file_range,
SR_SYS_syncfs,
SR_SYS__sysctl,
SR_SYS_sysfs,
SR_SYS_sysinfo,
SR_SYS_syslog,
SR_SYS_tee,
SR_SYS_tgkill,
SR_SYS_time,
SR_SYS_timer_create,
SR_SYS_timer_delete,
SR_SYS_timerfd_create,
SR_SYS_timerfd_gettime,
SR_SYS_timerfd_gettime64,
SR_SYS_timerfd_settime,
SR_SYS_timerfd_settime64,
SR_SYS_timer_getoverrun,
SR_SYS_timer_gettime,
SR_SYS_timer_gettime64,
SR_SYS_timer_settime,
SR_SYS_timer_settime64,
SR_SYS_times,
SR_SYS_tkill,
SR_SYS_truncate,
SR_SYS_truncate64,
SR_SYS_tuxcall,
SR_SYS_ugetrlimit,
SR_SYS_ulimit,
SR_SYS_umask,
SR_SYS_umount,
SR_SYS_umount2,
SR_SYS_uname,
SR_SYS_unlink,
SR_SYS_unlinkat,
SR_SYS_unshare,
SR_SYS_uselib,
SR_SYS_userfaultfd,
SR_SYS_ustat,
SR_SYS_utime,
SR_SYS_utimensat,
SR_SYS_utimensat_time64,
SR_SYS_utimes,
SR_SYS_vfork,
SR_SYS_vhangup,
SR_SYS_vm86,
SR_SYS_vm86old,
SR_SYS_vmsplice,
SR_SYS_vserver,
SR_SYS_wait4,
SR_SYS_waitid,
SR_SYS_waitpid,
SR_SYS_write,
SR_SYS_writev,
};

// ---
// Global variable
// ---

/**
 * @brief Get syscall definition index.
 * @param ptr Pointer to syscall definition.
 */
# define SCD_INDEX(ptr) ((ptr) - g_syscall_defs)

/**
 * @brief Array of syscall definitions.
 */
extern const syscall_def_t	g_syscall_defs[447];

#endif
